//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTM.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListFilter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListFilter()
        {
            this.TaskLists = new HashSet<TaskList>();
        }
    
        public int Id { get; set; }
        public bool Is_Show_Completed { get; set; }
        public bool Is_Ordered_Term { get; set; }
        public bool Is_Ordered_Prior { get; set; }
        public bool Is_Ordered_Tag { get; set; }
        public Nullable<System.DateTime> Selected_From_Date { get; set; }
        public Nullable<System.DateTime> Selected_To_Date { get; set; }
        public Nullable<int> Selected_Prior_Id { get; set; }
        public int Selected_Tag_Id { get; set; }
        public bool Is_Only_Favorites { get; set; }
    
        public virtual TaskPriority TaskPriority { get; set; }
        public virtual TaskTag TaskTag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskList> TaskLists { get; set; }
    }
}
