//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTM.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepeatTerm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RepeatTerm()
        {
            this.TaskSchedules = new HashSet<TaskSchedule>();
        }
    
        public int Id { get; set; }
        public string Repeat_Term { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskSchedule> TaskSchedules { get; set; }
    }
}
