//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTM.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskList()
        {
            this.TaskItems = new HashSet<TaskItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Order_Rank { get; set; }
        public int Color_R { get; set; }
        public int Color_G { get; set; }
        public int Color_B { get; set; }
        public int User_Id { get; set; }
        public int Filter_Id { get; set; }
    
        public virtual ListFilter ListFilter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskItem> TaskItems { get; set; }
        public virtual User User { get; set; }
    }
}
