//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTM.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskItem()
        {
            this.Subtasks = new HashSet<Subtask>();
            this.TaskFiles = new HashSet<TaskFile>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int List_Id { get; set; }
        public int Order_In_List { get; set; }
        public bool Is_Favorite { get; set; }
        public string Description { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public System.DateTime Delete_Date { get; set; }
        public int Schedule_Id { get; set; }
        public int Priority_Id { get; set; }
        public int Tag_Id { get; set; }
        public int Status_Id { get; set; }
        public int User_Id { get; set; }
        public int Doer_Id { get; set; }
    
        public virtual Doer Doer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subtask> Subtasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskFile> TaskFiles { get; set; }
        public virtual TaskList TaskList { get; set; }
        public virtual TaskSchedule TaskSchedule { get; set; }
        public virtual TaskPriority TaskPriority { get; set; }
        public virtual TaskTag TaskTag { get; set; }
        public virtual TaskStatus TaskStatu { get; set; }
        public virtual User User { get; set; }
    }
}
