//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTM.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskSchedule()
        {
            this.TaskItems = new HashSet<TaskItem>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Start_Term { get; set; }
        public Nullable<System.DateTime> End_Term { get; set; }
        public Nullable<bool> Is_Reminder_On { get; set; }
        public Nullable<System.DateTime> Reminder_Time { get; set; }
        public int RepeatTerm_Id { get; set; }
    
        public virtual RepeatTerm RepeatTerm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskItem> TaskItems { get; set; }
    }
}
