//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTaskManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int file_id { get; set; }
        public string file_name { get; set; }
        public string file_path { get; set; }
        public string guid_name { get; set; }
        public System.DateTime attach_date { get; set; }
        public int task_id { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
