//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTaskManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListFilter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListFilter()
        {
            this.TaskLists = new HashSet<TaskList>();
        }
    
        public int filter_id { get; set; }
        public bool is_show_completed { get; set; }
        public bool is_ordered_by_term { get; set; }
        public bool is_ordered_by_prior { get; set; }
        public bool is_ordered_by_tag { get; set; }
        public Nullable<System.DateTime> selected_from_date { get; set; }
        public Nullable<System.DateTime> selected_to_date { get; set; }
        public Nullable<int> selected_prior_id { get; set; }
        public int selected_tag_id { get; set; }
        public bool is_only_favorites { get; set; }
    
        public virtual Priority Priority { get; set; }
        public virtual Tag Tag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskList> TaskLists { get; set; }
    }
}
