//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTaskManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int schedule_id { get; set; }
        public Nullable<System.DateTime> start_term { get; set; }
        public Nullable<System.DateTime> end_term { get; set; }
        public Nullable<bool> is_every_day { get; set; }
        public Nullable<bool> is_every_week { get; set; }
        public Nullable<bool> is_every_month { get; set; }
        public Nullable<bool> is_every_year { get; set; }
        public Nullable<bool> is_reminder_on { get; set; }
        public Nullable<System.DateTime> reminder_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
