//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTaskManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Files = new HashSet<File>();
            this.Subtasks = new HashSet<Subtask>();
        }
    
        public int task_id { get; set; }
        public string task_name { get; set; }
        public int list_id { get; set; }
        public int order_in_list { get; set; }
        public bool is_favorite { get; set; }
        public string task_description { get; set; }
        public int schedule_id { get; set; }
        public int priority_id { get; set; }
        public int tag_id { get; set; }
        public int status_id { get; set; }
        public int user_id { get; set; }
        public int doer_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public System.DateTime delete_date { get; set; }
    
        public virtual Doer Doer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subtask> Subtasks { get; set; }
        public virtual Tag Tag { get; set; }
        public virtual TaskList TaskList { get; set; }
        public virtual User User { get; set; }
    }
}
