//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTaskManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskList()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int list_id { get; set; }
        public string list_name { get; set; }
        public int order_rank { get; set; }
        public int color_r { get; set; }
        public int color_g { get; set; }
        public int color_b { get; set; }
        public int user_id { get; set; }
        public int filter_id { get; set; }
    
        public virtual ListFilter ListFilter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual User User { get; set; }
    }
}
